2024-04-08 23:30:09,211 - INFO - start_polling: 527 - Start polling
2024-04-08 23:30:09,737 - INFO - _polling: 341 - Run polling for bot @tests_for_coders_bot id=6243740464 - 'тесты'
2024-04-08 23:30:16,489 - INFO - feed_update: 172 - Update id=377107247 is handled. Duration 2308 ms by bot id=6243740464
2024-04-08 23:30:19,805 - INFO - feed_update: 172 - Update id=377107248 is handled. Duration 812 ms by bot id=6243740464
2024-04-08 23:30:21,430 - INFO - feed_update: 172 - Update id=377107249 is handled. Duration 267 ms by bot id=6243740464
2024-04-08 23:30:25,126 - INFO - feed_update: 172 - Update id=377107250 is not handled. Duration 3 ms by bot id=6243740464
2024-04-04 20:59:03,221 - INFO - start_polling: 527 - Start polling
2024-04-04 20:59:03,804 - INFO - _polling: 341 - Run polling for bot @tests_for_coders_bot id=6243740464 - 'тесты'
2024-04-04 20:59:09,945 - WARNING - check_us: 24 - database disk image is malformed
2024-04-04 20:59:09,945 - ERROR - start_handler: 79 - database disk image is malformed
Traceback (most recent call last):
  File "C:\Users\kali\PycharmProjects\X\hand.py", line 75, in start_handler
    await start_db(msg.chat.id, msg.chat.username, msg.chat.first_name)
  File "C:\Users\kali\PycharmProjects\X\routers.py", line 11, in start_db
    curs.execute("INSERT INTO users (id_us, tag, name) VALUES (?, ?, ?)", (user_id, f_name, l_name))
sqlite3.DatabaseError: database disk image is malformed
2024-04-04 20:59:09,946 - INFO - feed_update: 172 - Update id=377106994 is handled. Duration 0 ms by bot id=6243740464
2024-04-04 20:59:26,667 - WARNING - check_us: 24 - database disk image is malformed
2024-04-04 20:59:26,667 - ERROR - start_handler: 79 - database disk image is malformed
Traceback (most recent call last):
  File "C:\Users\kali\PycharmProjects\X\hand.py", line 75, in start_handler
    await start_db(msg.chat.id, msg.chat.username, msg.chat.first_name)
  File "C:\Users\kali\PycharmProjects\X\routers.py", line 11, in start_db
    curs.execute("INSERT INTO users (id_us, tag, name) VALUES (?, ?, ?)", (user_id, f_name, l_name))
sqlite3.DatabaseError: database disk image is malformed
2024-04-04 20:59:26,667 - INFO - feed_update: 172 - Update id=377106995 is handled. Duration 0 ms by bot id=6243740464
